version: "3.4"
services:
  tiktok-recorder:
    image: overcoded/tiktok-live-recorder:latest
    restart: unless-stopped
    volumes:
      - ./output:/app/output
    environment:
      - USERS_TO_WATCH=highland_crystal

volumes:
  output:
    name: tiktok-live-recorder-output